server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_role?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: x.z.w.91
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

